"""added columns to models

Revision ID: 134280700462
Revises: ac954299b325
Create Date: 2024-05-03 11:07:14.516599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134280700462'
down_revision = 'ac954299b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
