"""added columns to models

Revision ID: 949d995f1924
Revises: 71561d173cd0
Create Date: 2024-05-03 11:03:28.292014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949d995f1924'
down_revision = '71561d173cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maturity_level', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('maturity_level')

    # ### end Alembic commands ###
